# Generated by Django 5.2.3 on 2026-02-15 09:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('drugs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReasonForVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='عنوان علت مراجعه')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'علت مراجعه',
                'verbose_name_plural': 'علل مراجعه',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='عنوان نتیجه درمان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'نتیجه درمان',
                'verbose_name_plural': 'نتایج درمان',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ویزیت')),
                ('incident_type', models.CharField(choices=[('none', 'بدون حادثه'), ('near_miss', 'شبه حادثه (Near Miss)'), ('minor', 'حادثه جزئی (Minor)'), ('major', 'حادثه ماژور (Major)')], default='none', max_length=20, verbose_name='نوع حادثه')),
                ('height_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))], verbose_name='قد (سانتی\u200cمتر)')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='وزن (کیلوگرم)')),
                ('blood_pressure', models.CharField(blank=True, max_length=15, null=True, verbose_name='فشار خون (مثال: 120/80)')),
                ('heart_rate', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ضربان قلب (در دقیقه)')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='دما (سانتی\u200cگراد)')),
                ('blood_sugar', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='قند خون (mg/dL)')),
                ('ecg_interpretation', models.TextField(blank=True, null=True, verbose_name='تفسیر نوار قلب')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات/شرح حال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ و زمان تکمیل')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('status', models.CharField(choices=[('pending', 'در حال بررسی'), ('referred', 'ارجاع شده'), ('completed', 'تکمیل شده')], default='pending', max_length=20, verbose_name='وضعیت ویزیت')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_visits', to=settings.AUTH_USER_MODEL, verbose_name='کاربر مسئول فعلی')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_visits', to=settings.AUTH_USER_MODEL, verbose_name='تکمیل کننده')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits_as_doctor', to=settings.AUTH_USER_MODEL, verbose_name='پزشک ثبت کننده')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='core.patient', verbose_name='بیمار')),
                ('reason_for_visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='visits.reasonforvisit', verbose_name='علت مراجعه')),
                ('treatment_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='visits.treatmentresult', verbose_name='نتیجه درمان')),
            ],
            options={
                'verbose_name': 'ویزیت',
                'verbose_name_plural': 'ویزیت\u200cها',
                'ordering': ['-visit_date'],
                'permissions': [('change_visit_status', 'Can change the status of visits'), ('refer_visit', 'Can refer visits to other users'), ('view_visit_report', 'Can view visit reports')],
            },
        ),
        migrations.CreateModel(
            name='VisitItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='تعداد تجویز شده')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات (برای این دارو)')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='drugs.drug', verbose_name='داروی تجویز شده')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='visits.visit', verbose_name='ویزیت')),
            ],
            options={
                'verbose_name': 'آیتم ویزیت',
                'verbose_name_plural': 'آیتم\u200cهای ویزیت',
                'unique_together': {('visit', 'drug')},
            },
        ),
    ]
