# Generated by Django 5.2.3 on 2025-09-06 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_visit_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='blood_sugar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='قند خون (mg/dL)'),
        ),
        migrations.AddField(
            model_name='visit',
            name='ecg_interpretation',
            field=models.TextField(blank=True, null=True, verbose_name='تفسیر نوار قلب'),
        ),
    ]
