# Generated by Django 5.2.3 on 2025-07-17 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='نام شرکت/مجموعه')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='تلفن')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='ایمیل')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('description', models.CharField(blank=True, max_length=300, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'شرکت/مجموعه',
                'verbose_name_plural': 'شرکت\u200cها/مجموعه\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('national_code', models.CharField(blank=True, help_text='در صورت اتباع خارجی نبودن، کد ملی اجباری است.', max_length=10, null=True, unique=True, verbose_name='کد ملی')),
                ('passport_number', models.CharField(blank=True, help_text='برای اتباع خارجی', max_length=50, null=True, unique=True, verbose_name='شماره پاسپورت')),
                ('is_foreign_national', models.BooleanField(default=False, verbose_name='تبعه خارجی')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره موبایل')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('gender', models.CharField(choices=[('M', 'مرد'), ('F', 'زن')], max_length=1, verbose_name='جنسیت')),
                ('blood_type', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='O+', max_length=3, null=True, verbose_name='گروه خونی')),
                ('insurance_type', models.CharField(blank=True, choices=[('social_security', 'تامین اجتماعی'), ('health_services', 'خدمات درمانی'), ('armed_forces', 'نیروهای مسلح'), ('other', 'سایر'), ('none', 'ندارد')], default='none', max_length=20, null=True, verbose_name='نوع بیمه')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='patient_pics/', verbose_name='عکس پروفایل')),
                ('allergies', models.CharField(blank=True, max_length=255, verbose_name='حساسیت\u200cها')),
                ('medical_history', models.TextField(blank=True, verbose_name='سوابق پزشکی')),
                ('occupation', models.CharField(blank=True, max_length=100, null=True, verbose_name='شغل')),
                ('last_periodic_examination_date', models.DateField(blank=True, null=True, verbose_name='آخرین معاینه دوره\u200cای')),
                ('personnel_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='کد پرسنلی')),
                ('is_approved', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('is_monitored', models.BooleanField(default=False, verbose_name='نیازمند پایش')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.company', verbose_name='شرکت/مجموعه')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ثبت کننده')),
            ],
            options={
                'verbose_name': 'بیمار',
                'verbose_name_plural': 'بیماران',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
