# Generated by Django 5.2.3 on 2025-09-08 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='height_cm',
            field=models.PositiveIntegerField(blank=True, help_text='قد بیمار به سانتی\u200cمتر', null=True, verbose_name='قد (سانتی\u200cمتر)'),
        ),
    ]
