# Generated by Django 5.2.3 on 2026-02-15 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drugs', '0001_initial'),
        ('visits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=255, null=True, verbose_name='موضوع')),
                ('body', models.TextField(verbose_name='متن پیام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('message_type', models.CharField(choices=[('general', 'عمومی'), ('notification', 'اطلاعیه'), ('urgent', 'فوری'), ('drug_request', 'درخواست دارو'), ('visit_note', 'یادداشت ویزیت')], default='general', max_length=20, verbose_name='نوع پیام')),
                ('parent_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='clinic_messages.message', verbose_name='پیام والد')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='فرستنده')),
            ],
            options={
                'verbose_name': 'پیام',
                'verbose_name_plural': 'پیام\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='message_attachments/', verbose_name='فایل')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام فایل')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ آپلود')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='clinic_messages.message', verbose_name='پیام')),
            ],
            options={
                'verbose_name': 'پیوست پیام',
                'verbose_name_plural': 'پیوست\u200cهای پیام',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='پیام اعلان')),
                ('notification_type', models.CharField(choices=[('general', 'عمومی'), ('message', 'پیام جدید'), ('visit_followup', 'پیگیری ویزیت'), ('drug_request_status', 'وضعیت درخواست دارو'), ('system', 'سیستم')], default='general', max_length=50, verbose_name='نوع اعلان')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ خوانده شدن')),
                ('link', models.URLField(blank=True, max_length=500, null=True, verbose_name='لینک مرتبط')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='گیرنده')),
                ('related_drug_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='drugs.drugrequest', verbose_name='درخواست داروی مرتبط')),
                ('related_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='clinic_messages.message', verbose_name='پیام مرتبط')),
                ('related_visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='visits.visit', verbose_name='ویزیت مرتبط')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='فرستنده')),
            ],
            options={
                'verbose_name': 'اعلان',
                'verbose_name_plural': 'اعلان\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده است؟')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ خوانده شدن')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients_data', to='clinic_messages.message', verbose_name='پیام')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='گیرنده')),
            ],
            options={
                'verbose_name': 'گیرنده پیام',
                'verbose_name_plural': 'گیرندگان پیام',
                'ordering': ['-message__created_at'],
                'unique_together': {('message', 'recipient')},
            },
        ),
    ]
