# Generated by Django 5.2.3 on 2025-06-29 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='نام دارو')),
                ('drug_code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='کد دارو')),
                ('generic_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام ژنریک')),
                ('form', models.CharField(choices=[('tablet', 'قرص'), ('capsule', 'کپسول'), ('syrup', 'شربت'), ('injection', 'آمپول/تزریقی'), ('cream', 'کرم/پماد'), ('gel', 'ژل'), ('solution', 'محلول'), ('suspension', 'سوسپانسیون'), ('drops', 'قطره'), ('suppository', 'شیاف'), ('aerosol', 'اسپری/افشانه'), ('powder', 'پودر'), ('vial', 'ویال'), ('other', 'سایر')], default='tablet', max_length=50, verbose_name='شکل دارویی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('min_stock_alert', models.IntegerField(default=10, verbose_name='حداقل موجودی هشدار')),
                ('reorder_point', models.IntegerField(default=20, verbose_name='نقطه سفارش مجدد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین بروزرسانی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'دارو',
                'verbose_name_plural': 'داروها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='نام تامین\u200cکننده')),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True, verbose_name='فرد تماس')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره تماس')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'تامین\u200cکننده',
                'verbose_name_plural': 'تامین\u200cکنندگان',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DrugRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات درخواست')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تایید شده'), ('rejected', 'رد شده'), ('completed', 'تکمیل شده'), ('canceled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت درخواست')),
                ('request_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ درخواست')),
                ('doctor_approval_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تایید پزشک')),
                ('doctor_rejection_reason', models.TextField(blank=True, null=True, verbose_name='دلیل رد (پزشک)')),
                ('supervisor_approval_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تایید سوپروایزر')),
                ('supervisor_rejection_reason', models.TextField(blank=True, null=True, verbose_name='دلیل رد (سوپروایزر)')),
                ('approved_by_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_drug_requests_as_doctor', to=settings.AUTH_USER_MODEL, verbose_name='تایید توسط پزشک')),
                ('approved_by_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_drug_requests_as_supervisor', to=settings.AUTH_USER_MODEL, verbose_name='تایید توسط سوپروایزر')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_drug_requests', to=settings.AUTH_USER_MODEL, verbose_name='درخواست کننده')),
            ],
            options={
                'verbose_name': 'درخواست دارو',
                'verbose_name_plural': 'درخواست\u200cهای دارو',
                'ordering': ['-request_date'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100, unique=True, verbose_name='شماره فاکتور')),
                ('invoice_date', models.DateField(verbose_name='تاریخ فاکتور')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مبلغ کل')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس (موقت)'), ('final', 'نهایی')], default='draft', max_length=10, verbose_name='وضعیت فاکتور')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت در سیستم')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین بروزرسانی')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drugs.supplier', verbose_name='تامین\u200cکننده')),
            ],
            options={
                'verbose_name': 'فاکتور خرید',
                'verbose_name_plural': 'فاکتورهای خرید',
                'ordering': ['-invoice_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت واحد')),
                ('expiry_date', models.DateField(verbose_name='تاریخ انقضا')),
                ('batch_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره بچ تولید شده')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugs.drug', verbose_name='دارو')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='drugs.purchaseinvoice', verbose_name='فاکتور')),
            ],
            options={
                'verbose_name': 'آیتم فاکتور خرید',
                'verbose_name_plural': 'آیتم\u200cهای فاکتور خرید',
            },
        ),
        migrations.CreateModel(
            name='DrugBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=100, unique=True, verbose_name='شماره بچ')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='موجودی')),
                ('manufacturing_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تولید')),
                ('expiry_date', models.DateField(verbose_name='تاریخ انقضا')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت خرید')),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='قیمت فروش')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='drugs.drug', verbose_name='دارو')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drugs.supplier', verbose_name='تامین\u200cکننده')),
            ],
            options={
                'verbose_name': 'بچ دارو',
                'verbose_name_plural': 'بچ\u200cهای دارو',
                'ordering': ['-expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='DrugRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_quantity', models.IntegerField(verbose_name='تعداد درخواستی')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugs.drug', verbose_name='دارو')),
                ('drug_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='drugs.drugrequest', verbose_name='درخواست دارو')),
            ],
            options={
                'verbose_name': 'آیتم درخواست دارو',
                'verbose_name_plural': 'آیتم\u200cهای درخواست دارو',
                'unique_together': {('drug_request', 'drug')},
            },
        ),
    ]
