# Generated by Django 5.2.3 on 2026-02-15 09:56

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='نام تامین\u200cکننده')),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True, verbose_name='فرد تماس')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره تماس')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'تامین\u200cکننده',
                'verbose_name_plural': 'تامین\u200cکنندگان',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام دارو')),
                ('generic_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام ژنریک')),
                ('form', models.CharField(choices=[('tablet', 'قرص'), ('capsule', 'کپسول'), ('syrup', 'شربت'), ('ampoule', 'آمپول'), ('injection', 'تزریقی'), ('vial', 'ویال'), ('inhaler', 'اسپری تنفسی'), ('aerosol', 'آئروسل'), ('solution', 'محلول'), ('ointment', 'پماد'), ('cream', 'کرم'), ('gel', 'ژل'), ('suspension', 'سوسپانسیون'), ('drop', 'قطره'), ('suppository', 'شیاف'), ('patch', 'چسب ترانس درمال'), ('granules', 'گرانول'), ('other', 'سایر')], default='قرص', max_length=50, verbose_name='شکل دارو')),
                ('unit', models.CharField(choices=[('packet', 'بسته'), ('box', 'جعبه'), ('bottle', 'بطری'), ('blister', 'ورق'), ('number', 'عدد'), ('vial', 'عدد (ویال)'), ('tube', 'تیوب'), ('can', 'قوطی'), ('other', 'سایر')], default='عدد', max_length=50, verbose_name='واحد بسته\u200cبندی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام شرکت')),
                ('drug_code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='کد دارو')),
                ('package_size', models.IntegerField(default=1, verbose_name='تعداد در هر بسته')),
                ('package_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع بسته\u200cبندی')),
                ('min_stock_alert', models.IntegerField(default=10, verbose_name='حداقل موجودی هشدار')),
                ('reorder_point', models.IntegerField(default=20, verbose_name='نقطه سفارش مجدد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین بروزرسانی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'دارو',
                'verbose_name_plural': 'داروها',
                'ordering': ['name'],
                'unique_together': {('name', 'form')},
            },
        ),
        migrations.CreateModel(
            name='DrugBarcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gtin', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='کد GTIN')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcodes', to='drugs.drug')),
            ],
        ),
        migrations.CreateModel(
            name='DrugRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_code', models.CharField(max_length=20, unique=True)),
                ('request_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('approved', 'تایید شده')], max_length=20)),
                ('assigned_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approver', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DrugRequestWorkflowLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, choices=[('pending', 'در انتظار بررسی'), ('approved', 'تایید شده'), ('rejected', 'رد شده'), ('completed', 'تکمیل شده'), ('canceled', 'لغو شده')], max_length=20, null=True, verbose_name='وضعیت قبلی')),
                ('new_status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تایید شده'), ('rejected', 'رد شده'), ('completed', 'تکمیل شده'), ('canceled', 'لغو شده')], max_length=20, verbose_name='وضعیت جدید')),
                ('action', models.CharField(max_length=100, verbose_name='اقدام انجام شده')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('drug_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_logs', to='drugs.drugrequest', verbose_name='درخواست دارو')),
            ],
            options={
                'verbose_name': 'لاگ گردش کار درخواست دارو',
                'verbose_name_plural': 'لاگ\u200cهای گردش کار درخواست دارو',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100, unique=True, verbose_name='شماره فاکتور')),
                ('invoice_date', models.DateField(verbose_name='تاریخ فاکتور')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مبلغ کل')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('final', 'نهایی شده'), ('paid', 'پرداخت شده'), ('pending', 'در انتظار پرداخت'), ('cancelled', 'لغو شده')], default='draft', max_length=10, verbose_name='وضعیت فاکتور')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت در سیستم')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین بروزرسانی')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drugs.supplier', verbose_name='تامین\u200cکننده')),
            ],
            options={
                'verbose_name': 'فاکتور خرید',
                'verbose_name_plural': 'فاکتورهای خرید',
                'ordering': ['-invoice_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DrugRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_quantity', models.IntegerField(verbose_name='تعداد درخواستی')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات آیتم')),
                ('approved_quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='تعداد تایید شده')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugs.drug', verbose_name='دارو')),
                ('drug_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='drugs.drugrequest', verbose_name='درخواست دارو')),
            ],
            options={
                'verbose_name': 'آیتم درخواست دارو',
                'verbose_name_plural': 'آیتم\u200cهای درخواست دارو',
                'unique_together': {('drug_request', 'drug')},
            },
        ),
        migrations.CreateModel(
            name='PurchaseInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت واحد')),
                ('expiry_date', models.DateField(verbose_name='تاریخ انقضا')),
                ('batch_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره بچ تولید شده')),
                ('total_item_price', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=20, verbose_name='مبلغ جزء')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugs.drug', verbose_name='دارو')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='drugs.purchaseinvoice', verbose_name='فاکتور')),
            ],
            options={
                'verbose_name': 'آیتم فاکتور خرید',
                'verbose_name_plural': 'آیتم\u200cهای فاکتور خرید',
                'unique_together': {('invoice', 'drug', 'batch_number')},
            },
        ),
        migrations.CreateModel(
            name='DrugBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=100, verbose_name='شماره بچ')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='موجودی')),
                ('manufacturing_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تولید')),
                ('expiry_date', models.DateField(verbose_name='تاریخ انقضا')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='قیمت خرید')),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='قیمت فروش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('is_temporary', models.BooleanField(default=False, help_text='در صورت انتخاب، این موجودی پس از انبارگردانی حذف خواهد شد.', verbose_name='موجودی موقت (کاذب)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='drugs.drug', verbose_name='دارو')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drugs.supplier', verbose_name='تامین\u200cکننده')),
            ],
            options={
                'verbose_name': 'بچ دارو',
                'verbose_name_plural': 'بچ\u200cهای دارو',
                'ordering': ['expiry_date'],
                'unique_together': {('drug', 'batch_number')},
            },
        ),
    ]
