# Generated by Django 5.2.3 on 2025-07-17 19:27

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='unit',
            field=models.CharField(choices=[('packet', 'بسته'), ('box', 'جعبه'), ('bottle', 'بطری'), ('blister', 'ورق'), ('ampoule', 'عدد'), ('vial', 'عدد (ویال)'), ('tube', 'تیوب'), ('can', 'قوطی'), ('other', 'سایر')], default='عدد', max_length=50, verbose_name='واحد بسته\u200cبندی'),
        ),
        migrations.AddField(
            model_name='drugbatch',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceitem',
            name='total_item_price',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=20, verbose_name='مبلغ جزء'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('final', 'نهایی شده'), ('paid', 'پرداخت شده'), ('pending', 'در انتظار پرداخت'), ('cancelled', 'لغو شده')], default='draft', max_length=10, verbose_name='وضعیت فاکتور'),
        ),
        migrations.AlterUniqueTogether(
            name='purchaseinvoiceitem',
            unique_together={('invoice', 'drug', 'batch_number')},
        ),
        migrations.CreateModel(
            name='DrugRequestWorkflowLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, choices=[('pending', 'در انتظار بررسی'), ('approved', 'تایید شده'), ('rejected', 'رد شده'), ('completed', 'تکمیل شده'), ('canceled', 'لغو شده')], max_length=20, null=True, verbose_name='وضعیت قبلی')),
                ('new_status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تایید شده'), ('rejected', 'رد شده'), ('completed', 'تکمیل شده'), ('canceled', 'لغو شده')], max_length=20, verbose_name='وضعیت جدید')),
                ('action', models.CharField(max_length=100, verbose_name='اقدام انجام شده')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('drug_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_logs', to='drugs.drugrequest', verbose_name='درخواست دارو')),
            ],
            options={
                'verbose_name': 'لاگ گردش کار درخواست دارو',
                'verbose_name_plural': 'لاگ\u200cهای گردش کار درخواست دارو',
                'ordering': ['-timestamp'],
            },
        ),
    ]
