# Generated by Django 5.2.3 on 2025-07-20 08:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0002_drug_unit_drugbatch_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drugrequest',
            name='approved_by_doctor',
        ),
        migrations.RemoveField(
            model_name='drugrequest',
            name='approved_by_supervisor',
        ),
        migrations.RemoveField(
            model_name='drugrequest',
            name='doctor_approval_date',
        ),
        migrations.RemoveField(
            model_name='drugrequest',
            name='doctor_rejection_reason',
        ),
        migrations.RemoveField(
            model_name='drugrequest',
            name='supervisor_approval_date',
        ),
        migrations.RemoveField(
            model_name='drugrequest',
            name='supervisor_rejection_reason',
        ),
        migrations.AddField(
            model_name='drugrequest',
            name='assigned_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_drug_requests', to=settings.AUTH_USER_MODEL, verbose_name='مسئول بررسی/تایید'),
        ),
        migrations.AddField(
            model_name='drugrequest',
            name='request_code',
            field=models.CharField(blank=True, max_length=25, unique=True, verbose_name='شماره درخواست'),
        ),
        migrations.AlterField(
            model_name='drugrequest',
            name='request_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ درخواست (امضا)'),
        ),
        migrations.AlterField(
            model_name='drugrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_drug_requests', to=settings.AUTH_USER_MODEL, verbose_name='درخواست کننده (امضا)'),
        ),
    ]
