# Generated by Django 5.2.3 on 2025-07-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0003_remove_drugrequest_approved_by_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugrequestitem',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات آیتم'),
        ),
    ]
