# Generated by Django 5.2.3 on 2025-07-20 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0004_drugrequestitem_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drugrequest',
            options={},
        ),
        migrations.AddField(
            model_name='drugrequestitem',
            name='approved_quantity',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='تعداد تایید شده'),
        ),
        migrations.AlterField(
            model_name='drugrequest',
            name='assigned_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='drugrequest',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='drugrequest',
            name='request_code',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='drugrequest',
            name='request_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='drugrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='drugrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('approved', 'تایید شده')], max_length=20),
        ),
    ]
