# Generated by Django 5.2.3 on 2025-07-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0005_alter_drugrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugrequest',
            name='request_code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
