# Generated by Django 5.2.3 on 2025-09-06 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0006_alter_drugrequest_request_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugbatch',
            name='is_temporary',
            field=models.BooleanField(default=False, help_text='در صورت انتخاب، این موجودی پس از انبارگردانی حذف خواهد شد.', verbose_name='موجودی موقت (کاذب)'),
        ),
    ]
