# Generated by Django 5.2.3 on 2026-02-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawVisitScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='scans/%Y/%m/%d/', verbose_name='تصویر برگه')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('voice', models.ImageField(upload_to='scans/%Y/%m/%d/', verbose_name='تصویر برگه')),
            ],
            options={
                'verbose_name': 'اسکن برگه ویزیت',
                'verbose_name_plural': 'اسکن\u200cهای برگه ویزیت',
            },
        ),
    ]
